export const metadata = [

        {
            id:0,
            option:'Giraffe',
            link:'https://ipfs.io/ipfs/QmYiUTxEqrsFUVuHTuDvJiNyrsssSapZPX4pHfPic2wyEC',
            traits:{
                trait_1:'Yellow',
                trait_2:'Left'
            }
        },
        {
            id:1,
            option:'Horse',
            link:'https://ipfs.io/ipfs/QmNjDzgWZU7K6Qk8m4iAZFcSuDXfi8YAaXofoNU9PH8emA',
            traits:{
                trait_1:'White',
                trait_2:'Middle'
            }
        },
        {
            id:2,
            option:'Duck',
            link:'https://ipfs.io/ipfs/QmWieRzW7TUF33rY3MRfK4eHL8mg5oYmDB2k48Kv6BSCJZ',
            traits:{
                trait_1:'Brown',
                trait_2:'Right'
            }
        }
]
